name: Deploy

on:
  push:
    branches:
      - master
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.15.1]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      # Build
      - run: npm ci
      - run: npm run build
      # Deploy
      - run:
          cd dist && rsync -rvt -e "ssh -i $HOME/.ssh/key -o
          StrictHostKeyChecking=no -p 777" --delete --archive --compress .
          renton@kikel.net:~/www/dev.kikel.net/
